### ISSUE TITLE
how do you run this?

### ISSUE THREAD

**Issue by stortzm** [achow101/stratum-watcher#3]
I've tried running this on my pycharm, to no result; 
I'm missing a step or completely oblivious on how it's supposed to be run

**Comment by achow101** [comment]
I'm not sure how to run in this in pycharm as I do not use it. The simplest way to run this is to just open up a terminal and do `./watchmany.py`. Currently it also requires that a node be running locally too.

**Comment by stortzm** [comment]
that was the issue, the node wasn't running
